### ISSUE TITLE
Remove  old 1.0-5 build from TigerOS mirror

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tigeros-ui-tweaks#9]

**Comment by ct-martin** [comment]
I haven't imported my SSH key to my laptop yet and my desktop is still
offline; please ping me in Slack on Monday. Also, nothing will break if we
leave a couple versions on the mirror; we don't need to actively remove old
versions. On the contrary, it's helpful in case we mess up and someone
needs to downgrade.

**Comment by Tjzabel** [comment]
It was decided we would keep recent old versions of packages for the time being.
